version: v1
# connectfour, tictactoe (*** NOTE ***: tic-tac-toe game is not properly implemented. I just wanted to play around and load different game at runtime via config)
game: 'connectfour'

# oneplayer, twoplayer
game-type: 'oneplayer'

# 1 - easy,  3, medium,  5 - hard,  7 - expert, 9 - you cant win
difficulty-level: 3

# algorithm 
algorithm: 'minmax'