version: v1
# connectfour, tictactoe (*** NOTE ***: tic-tac-toe game is not properly implemented. I just wanted to play around and load different game at runtime via config)
game: 'connectfour'

# oneplayer, twoplayer
num-of-players: 'one'

# 1 - easy,  3, medium,  5 - hard,  7 - expert, 9 - you cant win
difficulty-level: 3

# algorithm 
algorithm: 'minmax'

#Postgres sql connection string
dbconn: 'postgresql://gamer:pass1234@localhost/board_games?sslmode=disable'